import crypto from 'node:crypto';
import { ApiError } from '../lib/errors.js';

const SAFE_KEY = /^[a-z0-9][a-z0-9/._-]{0,398}$/;

/**
 * Storage keys are generated by us, never taken from user input. This guard
 * exists because keys also arrive from the database and from admin requests.
 */
export const assertSafeKey = (key: string): string => {
  const normalized = key.replace(/\\/g, '/').replace(/^\/+/, '');
  if (!SAFE_KEY.test(normalized)) {
    throw ApiError.badRequest('Invalid media key.');
  }
  if (normalized.includes('..') || normalized.includes('//')) {
    throw ApiError.badRequest('Invalid media key.');
  }
  return normalized;
};

/** `products/2026/09/<random>.webp` — the original filename is never reused. */
export const buildStorageKey = (prefix: string, extension: string, when = new Date()): string => {
  const year = when.getUTCFullYear();
  const month = String(when.getUTCMonth() + 1).padStart(2, '0');
  const random = crypto.randomBytes(16).toString('hex');
  const ext = extension.replace(/[^a-z0-9]/gi, '').toLowerCase() || 'bin';
  return assertSafeKey(`${prefix}/${year}/${month}/${random}.${ext}`);
};

export const withSuffix = (key: string, suffix: string, extension: string): string => {
  const lastDot = key.lastIndexOf('.');
  const stem = lastDot === -1 ? key : key.slice(0, lastDot);
  return assertSafeKey(`${stem}${suffix}.${extension}`);
};
